title: Aninda Ghosh # your name (or website title) here
logo: "/images/profile_pic.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  M.S. Robotics and Autonomous Systems 
  Artificial Intelligence  
  <br>
  Arizona State University
  <br>
  (+1) 623 283 8611
  <br>
  ghosh.private@gmail.com 
  <br><br>
  <a href="https://www.linkedin.com/in/aghosh57/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
